package View;

import javax.swing.JFrame;

/** Creates new form NewJFrame */
public class IhmImpl extends JFrame{

public IhmImpl() {
    initComponents();
}

/** This method is called from within the constructor to
 * initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is
 * always regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jButton_Start = new javax.swing.JButton();
    jButton_Stop = new javax.swing.JButton();
    jButton_Inc = new javax.swing.JButton();
    jButton_Dec = new javax.swing.JButton();
    jSlider1 = new javax.swing.JSlider();
    jPanel_Led1 = new javax.swing.JPanel();
    jPanel_Led2 = new javax.swing.JPanel();
    jLabel_Led1 = new javax.swing.JLabel();
    jLabel_Led2 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jLabel1.setBackground(new java.awt.Color(153, 255, 153));
    jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
    jLabel1.setText("jLabel1");
    jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

    jButton_Start.setText("START");
    jButton_Start.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton_StartActionPerformed(evt);
        }
    });

    jButton_Stop.setText("STOP");

    jButton_Inc.setText("INC");

    jButton_Dec.setText("DEC");

    jSlider1.setMaximum(8);

    javax.swing.GroupLayout jPanel_Led1Layout = new javax.swing.GroupLayout(jPanel_Led1);
    jPanel_Led1.setLayout(jPanel_Led1Layout);
    jPanel_Led1Layout.setHorizontalGroup(
        jPanel_Led1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 27, Short.MAX_VALUE)
    );
    jPanel_Led1Layout.setVerticalGroup(
        jPanel_Led1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 30, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout jPanel_Led2Layout = new javax.swing.GroupLayout(jPanel_Led2);
    jPanel_Led2.setLayout(jPanel_Led2Layout);
    jPanel_Led2Layout.setHorizontalGroup(
        jPanel_Led2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 31, Short.MAX_VALUE)
    );
    jPanel_Led2Layout.setVerticalGroup(
        jPanel_Led2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 31, Short.MAX_VALUE)
    );

    jLabel_Led1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel_Led1.setText("LED 1");

    jLabel_Led2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel_Led2.setText("LED 2");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(59, 59, 59)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton_Start)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_Stop))
                        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 445, Short.MAX_VALUE)
                            .addComponent(jPanel_Led2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(449, 449, 449)
                            .addComponent(jPanel_Led1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(110, 110, 110)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton_Inc)
                                    .addGap(98, 98, 98)
                                    .addComponent(jButton_Dec))
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel_Led2))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(739, Short.MAX_VALUE)
                    .addComponent(jLabel_Led1)))
            .addGap(39, 39, 39))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(58, 58, 58)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jLabel_Led1)
                .addComponent(jPanel_Led1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(75, 75, 75)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jPanel_Led2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel_Led2))
            .addGap(12, 12, 12)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton_Start)
                .addComponent(jButton_Stop)
                .addComponent(jButton_Inc)
                .addComponent(jButton_Dec))
            .addContainerGap(32, Short.MAX_VALUE))
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(113, 113, 113)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(100, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(33, 33, 33)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(43, Short.MAX_VALUE))
    );

    pack();
}// </editor-fold>//GEN-END:initComponents

private void jButton_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_StartActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_jButton_StartActionPerformed

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {

        public void run() {
            new IhmImpl().setVisible(true);
        }
    });
}
// Variables declaration - do not modify//GEN-BEGIN:variables
private javax.swing.JButton jButton_Dec;
private javax.swing.JButton jButton_Inc;
private javax.swing.JButton jButton_Start;
private javax.swing.JButton jButton_Stop;
private javax.swing.JLabel jLabel1;
private javax.swing.JLabel jLabel_Led1;
private javax.swing.JLabel jLabel_Led2;
private javax.swing.JPanel jPanel1;
private javax.swing.JPanel jPanel_Led1;
private javax.swing.JPanel jPanel_Led2;
private javax.swing.JSlider jSlider1;
// End of variables declaration//GEN-END:variables
}

